#:schema node_modules/wrangler/config-schema.json
name = "strict-dynamic-csp-v1"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[vars]
ENFORCE_CSP = "true"
STYLE_NONCE = "true"
